Server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://172.27.96.1:8761/eureka

spring:
  application:
    name: PRODUCT-SERVICE

